/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_imperialsoupgmail_tesseractexample_MyNDK */

#ifndef _Included_com_imperialsoupgmail_tesseractexample_MyNDK
#define _Included_com_imperialsoupgmail_tesseractexample_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imperialsoupgmail_tesseractexample_MyNDK
 * Method:    getMyString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_imperialsoupgmail_tesseractexample_MyNDK_getMyString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
