/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_com_opencvconfigure_MainActivity */
#include "stdio.h"
#include "opencv2/opencv.hpp"

using namespace std;
using namespace cv;
#ifndef _Included_com_example_com_opencvconfigure_MainActivity
#define _Included_com_example_com_opencvconfigure_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_com_opencvconfigure_MainActivity
 * Method:    convertGray
 * Signature: (JJ)I
 */
int goGray(Mat img, Mat &mGray);

JNIEXPORT jint JNICALL Java_com_imperialsoupgmail_tesseractexample_MainActivity_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
