/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "stdio.h"
#include "opencv2/opencv.hpp"
/* Header for class com_imperialsoupgmail_tesseractexample_MyNDK */
using namespace cv;
using namespace std;
#ifndef _Included_com_imperialsoupgmail_tesseractexample_MyNDK
#define _Included_com_imperialsoupgmail_tesseractexample_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imperialsoupgmail_tesseractexample_MyNDK
 * Method:    converGray
 * Signature: (JJ)I
 */
int toGray(Mat, Mat&);
JNIEXPORT jint JNICALL Java_com_imperialsoupgmail_tesseractexample_MyNDK_converGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
